version: 0.0
os: linux

files:
  - source: /
    destination: /data/oramsys  # Update this path to your application's deployment directory

file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/build_frontend.sh
      timeout: 600
      runas: ubuntu
